#
# Copyright 2022 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0
#

astarte_library = ASTARTE_LIBRARY
interfaces_directory = "/usr/share/edgehog-astarte-interfaces"
store_directory = "/var/lib/edgehog-device-runtime/"
download_directory = "/var/tmp/"

[astarte_device_sdk]
device_id = ASTARTE_DEVICE_ID
pairing_token = ASTARTE_PAIRING_JWT
credentials_secret = ASTARTE_CREDENTIAL_SECRET
pairing_url = ASTARTE_PAIRING_BASE_URL
realm = ASTARTE_REALM

[astarte_message_hub]
endpoint = ASTARTE_MESSAGE_HUB_ENDPOINT

[[telemetry_config]]
interface_name = "io.edgehog.devicemanager.StorageUsage"
enabled = false
period = 0
